# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'MarvelApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp
 pod 'Alamofire'
 pod 'SwiftyJSON'
 
end

target 'MarvelAppUITests' do
  pod 'Alamofire'

  end

target 'MarvelAppTests' do
pod 'Alamofire'

end
